### ISSUE TITLE
'npm run demo' fails

### ISSUE THREAD

**Issue by iyogeshjoshi** [thlorenz/peacock#1]
Hi, I tried running demo for peacock, but it always fails saying `Couldn't get a file descriptor referring to the console`

[here](http://pastebin.com/vycisQTK) is the pastebin link to debug-log and console log output.

**Comment by thlorenz** [comment]
What OS are you on? Sounds like you got trouble with your stdout?

**Comment by iyogeshjoshi** [comment]
I'm using Ubuntu. As you say it's stdout problem do you have anything or test to check whether it's stdout or something else?
